name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - run: |
        npm install
        npm run all

  docker-integration: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        base:
          - core18
          - core20
          - core22
        arch:
          - ''
          - amd64
          - armhf
          - arm64
          - ppc64el
        runner:
          - ubuntu-latest
        include:
          - base: core
            arch: ''
            runner: ubuntu-20.04
          - base: core
            arch: i386
            runner: ubuntu-20.04
          - base: core
            arch: amd64
            runner: ubuntu-20.04
          - base: core
            arch: armhf
            runner: ubuntu-20.04
          - base: core
            arch: arm64
            runner: ubuntu-20.04
          - base: core18
            arch: i386
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch }}

  podman-integration: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        base:
          - core20
          - core22
        arch:
          - name: ''
            runner: ubuntu-latest
          - name: ''
            runner: [self-hosted, linux, ARM64]
          - name: amd64
            runner: ubuntu-latest
          - name: arm64
            runner: [self-hosted, linux, ARM64]
        include:
          - base: core
            arch:
              name: ''
              runner: ubuntu-20.04
          - base: core
            arch:
              name: i386
              runner: ubuntu-20.04
          - base: core
            arch:
              name: amd64
              runner: ubuntu-20.04
          - base: core18
            arch:
              name: i386
              runner: ubuntu-latest
          - base: core18
            arch:
              name: amd64
              runner: ubuntu-latest
    runs-on: ${{ matrix.arch.runner }}
    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v3
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch.name }}
        use-podman: 'true'
