name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all

  integration: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        base:
          - core
          - core18
          - core20
          - core22
        arch:
          - ''
          - amd64
          - armhf
          - arm64
          - ppc64el
        usePodman:
          - ''
          - 'true'
          - 'false'
        include:
          - base: core
            arch: i386
            usePodman: 'false'
          - base: core
            arch: i386
            usePodman: 'true'
          - base: core18
            arch: i386
            usePodman: 'false'
          - base: core18
            arch: i386
            usePodman: 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v3
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch }}
        use-podman: ${{ matrix.usePodman }}
