name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - run: |
        npm install
        npm run all

  integration: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        base:
          - core18
          - core20
          - core22
        arch:
          - ''
          - amd64
          - armhf
          - arm64
          - ppc64el
        usePodman:
          - ''
          - 'true'
          - 'false'
        runner:
          - ubuntu-latest
        include:
          - base: core
            arch: ''
            usePodman: 'false'
            runner: ubuntu-20.04
          - base: core
            arch: ''
            usePodman: 'true'
            runner: ubuntu-20.04
          - base: core
            arch: i386
            usePodman: 'false'
            runner: ubuntu-20.04
          - base: core
            arch: i386
            usePodman: 'true'
            runner: ubuntu-20.04
          - base: core
            arch: amd64
            usePodman: 'false'
            runner: ubuntu-20.04
          - base: core
            arch: amd64
            usePodman: 'true'
            runner: ubuntu-20.04
          - base: core
            arch: armhf
            usePodman: 'false'
            runner: ubuntu-20.04
          - base: core
            arch: armhf
            usePodman: 'true'
            runner: ubuntu-20.04
          - base: core
            arch: arm64
            usePodman: 'false'
            runner: ubuntu-20.04
          - base: core
            arch: arm64
            usePodman: 'true'
            runner: ubuntu-20.04
          - base: core18
            arch: i386
            usePodman: 'false'
            runner: ubuntu-latest
          - base: core18
            arch: i386
            usePodman: 'true'
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch }}
        use-podman: ${{ matrix.usePodman }}
